server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true（服务的消费者可以不注册，这里可以改为false）。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息（获取已注册的服务），默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #将order服务在eureka集群中注册
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
