server:
  port: 80

eureka:
  client:
    #服务的消费者，可以不在注册中心中注册
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间（OpenFeign默认等待1秒钟，超过后报错，这里指定为5秒）
  ReadTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.holun.springcloud.client.PaymentFeignService: debug