server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: haolun

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true（注册服务）。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #将payment服务在eureka集群中注册
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #心跳检测与续约时间
    #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)。这里设置为每隔一秒发送
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  #指明mapper映射文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #为指定包下的实体类取别名
  type-aliases-package: com.holun.springcloud.entity
  configuration:
    #使用jdbc的getGeneratedKeys获取数据库自增主键值
    use-generated-keys: true
    #使用列别名替换列名
    use-column-label: true
    #开启驼峰命名转换:Table{create_time} -> Entity{createTime}
    map-underscore-to-camel-case: true