server:
  port: 7003

spring:
  application:
    name: eureka-ser3

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7003.com
  server:
    #关闭eureka自我保护机制
    enable-self-preservation: false
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #集群就指向其它eureka server
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机就是7002自己
      #defaultZone: http://eureka7003.com:7003/eureka/
